project = "Keep Moving"
title = "DST Mod Keep Moving | LDoc"
description = "dst-mod-keep-moving"
full_description = [[Mod for the game [Don\'t Starve Together](https://www.klei.com/games/dont-starve-together) to keep moving in a certain direction or on a road.]] .. "\n\n" ..
    [[- **Source Code:** [https://github.com/victorpopkov/dst-mod-keep-moving](https://github.com/victorpopkov/dst-mod-keep-moving)]] .. "\n" ..
    [[- **Steam Workshop:** [https://steamcommunity.com/app/322330/workshop/](https://steamcommunity.com/app/322330/workshop/)]]

dir = "doc"
file = "./scripts/"
format = "markdown"
readme = "readme"
sort_modules = true
style = "./doc/ldoc/"
use_markdown_titles = true
